<?php

return array (
  0 => 
  array (
    'basename' => 'TwoAuthors',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoAuthors',
    'namespace' => 'Modules\\TwoAuthors',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoAuthors/',
    'slug' => 'two_authors',
    'type' => 'module',
  ),
  1 => 
  array (
    'basename' => 'TwoBackend',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Themes/TwoBackend',
    'namespace' => 'Themes\\TwoBackend',
    'order' => 9001,
    'path' => 'F:/two-app-main/themes/TwoBackend/',
    'slug' => 'two_backend',
    'type' => 'theme',
  ),
  2 => 
  array (
    'basename' => 'TwoBlocks',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoBlocks',
    'namespace' => 'Modules\\TwoBlocks',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoBlocks/',
    'slug' => 'two_blocks',
    'type' => 'module',
  ),
  3 => 
  array (
    'basename' => 'TwoBoost',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Themes/TwoBoost',
    'namespace' => 'Themes\\TwoBoost',
    'order' => 9001,
    'path' => 'F:/two-app-main/themes/TwoBoost/',
    'slug' => 'two_boost',
    'type' => 'theme',
  ),
  4 => 
  array (
    'basename' => 'TwoChat',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoChat',
    'namespace' => 'Modules\\TwoChat',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoChat/',
    'slug' => 'two_chat',
    'type' => 'module',
  ),
  5 => 
  array (
    'basename' => 'TwoCore',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoCore',
    'namespace' => 'Modules\\TwoCore',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoCore/',
    'slug' => 'two_core',
    'type' => 'module',
  ),
  6 => 
  array (
    'basename' => 'TwoGroupes',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoGroupes',
    'namespace' => 'Modules\\TwoGroupes',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoGroupes/',
    'slug' => 'two_groupes',
    'type' => 'module',
  ),
  7 => 
  array (
    'basename' => 'TwoNews',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoNews',
    'namespace' => 'Modules\\TwoNews',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoNews/',
    'slug' => 'two_news',
    'type' => 'module',
  ),
  8 => 
  array (
    'basename' => 'TwoPermissions',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoPermissions',
    'namespace' => 'Modules\\TwoPermissions',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoPermissions/',
    'slug' => 'two_permissions',
    'type' => 'module',
  ),
  9 => 
  array (
    'basename' => 'TwoRoles',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoRoles',
    'namespace' => 'Modules\\TwoRoles',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoRoles/',
    'slug' => 'two_roles',
    'type' => 'module',
  ),
  10 => 
  array (
    'basename' => 'TwoThemes',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoThemes',
    'namespace' => 'Modules\\TwoThemes',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoThemes/',
    'slug' => 'two_themes',
    'type' => 'module',
  ),
  11 => 
  array (
    'basename' => 'TwoUsers',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoUsers',
    'namespace' => 'Modules\\TwoUsers',
    'order' => 9001,
    'path' => 'F:/two-app-main/modules/TwoUsers/',
    'slug' => 'two_users',
    'type' => 'module',
  ),
);
